import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/header";
import { CustomOpenMenu } from "../components/menus/customOpenMenu";
import { Providers } from "./provider";
import { connectToMongoDB } from "@/lib/mongodb";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  connectToMongoDB();

  return (
    <html lang="en">
      <body className={`antialiased  w-full text-xl`}>
        <Providers>
          <Header />
          {children}
          <CustomOpenMenu />
        </Providers>
      </body>
    </html>
  );
}
