import "./globals.css";
import { Providers } from "./provider";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased  w-full text-xl`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
