import "./globals.css";
import { Providers } from "./provider";
import { connectToMongoDB } from "@/lib/mongodb";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

await connectToMongoDB();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased  w-full text-xl`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
